###
POST http://localhost:8000/v1/request
Content-Type: application/json

{
  "ingredients": [
    "샐러리", "토마토", "월계수","양파", "돼지 목살"
  ]
}

###
POST http://localhost:8000/v1/request
Content-Type: application/json

{ingredients: ["브로콜리", "양파"], more: false, excludeIngredients: []}

###
GET http://localhost:8000/v1/yegeo/ingredients

###
PUT http://localhost:8000/v1/yegeo/ingredients
Content-Type: application/json

{
  "ingredients": [
    "토마토", "바질", "파스타면", "마늘", "양파"
  ]
}


###
GET http://localhost:8000/base_ingredients